---
- name: Gather OS specific variables for Nagios
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"

- name: Install Nagios packages
  package:
    name: "{{ nagios_packages }}"
    state: present
  tags:
    - configuration

- name: Create Nagios conf.d directory
  file:
    path: "{{ nagios_confd_dir }}"
    owner: root
    group: "{{ nagios_group }}"
    mode: 0750
    state: directory
  tags:
    - configuration

- name: Copy Nagios dropin configurations
  copy:
    src: "{{ item }}"
    dest: "{{ nagios_confd_dir }}"
    owner: root
    group: "{{ nagios_group }}"
    mode: 0640
  with_fileglob:
    - nagios/conf.d/*
  notify: restart nagios
  tags:
    - packages
